# Generated by Django 4.0.5 on 2022-06-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_student_delete_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='spec',
            field=models.TextField(max_length=50, verbose_name='Специальность'),
        ),
    ]
